node_js:
- "node"

script:
- echo "Verification des styles"
- npm i jshint --save-dev
- node_modules/.bin/jshint src
- echo "toto"
- npm install
- npm test

deploy:
provider:pages
skip_cleanup:true
github_token:$deploy
keep_history: true
on : 
 branch: master
